# Generated by Django 5.0.7 on 2024-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationthings',
            name='id',
        ),
        migrations.AddField(
            model_name='notificationthings',
            name='user_id',
            field=models.CharField(default='dupA0005', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='notificationthings',
            table='notification_settings',
        ),
    ]
