# Generated by Django 5.0.7 on 2024-08-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthorization', '0002_remove_notificationthings_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationthings',
            name='user_id',
            field=models.CharField(default='dupA0002', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
