# Generated by Django 5.0.7 on 2024-08-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthorization', '0003_alter_notificationthings_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationthings',
            name='user_id',
            field=models.CharField(default='dupA0005', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
