# Generated by Django 5.0.7 on 2024-09-04 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthorization', '0004_alter_notificationthings_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatWallet',
            fields=[
                ('fiat_wallet_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('fiat_wallet_type', models.CharField(max_length=50)),
                ('fiat_wallet_currency', models.CharField(max_length=10)),
                ('fiat_wallet_address', models.CharField(editable=False, max_length=66, unique=True)),
                ('fiat_wallet_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('fiat_wallet_created_time', models.DateTimeField(auto_now_add=True)),
                ('fiat_wallet_updated_time', models.DateTimeField(auto_now=True)),
                ('fiat_wallet_phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?1?\\d{9,15}$')])),
                ('fiat_wallet_username', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currency_converter_fiatwallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?1?\\d{9,15}$')])),
                ('users_data_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'currency_converter_user',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificationthings',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='password',
            options={'managed': False},
        ),
    ]
