# Generated by Django 5.0.7 on 2024-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthorization', '0005_fiatwallet_user_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('recovery_phrases', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=10)),
                ('creation_state', models.CharField(max_length=10)),
                ('balance', models.CharField(max_length=20)),
                ('sui_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelTable(
            name='fiatwallet',
            table='fiat_wallet',
        ),
    ]
