# Generated by Django 5.0.7 on 2024-09-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthorization', '0005_fiatwallet_user_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelTable(
            name='fiatwallet',
            table='fiat_wallet',
        ),
    ]
